
name: Compile binary & installer
on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  Windows-build:
    permissions: write-all
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.9']
        python-arch: [x64] #, x86]
        
    runs-on: ${{matrix.os}}

    env:
      EXPECTED_ISCC_PATH: '${env:ProgramFiles(x86)}\Inno Setup 6\iscc.exe'
      INSTALLER_DIR: 'installer_build'
      BUILD_NAME_BASE: 'positioner_installer'
      SCRIPT_BUILD_PATH: 'build\exe'
      
    steps:
      - name: Set up ISCC_PATH
        run: |
          (&{If((Test-Path "${{env.EXPECTED_ISCC_PATH}}" -PathType Leaf) -ne $True) {echo "ISCC not exist(${{env.EXPECTED_ISCC_PATH}})";exit 1}})
          echo "ISCC_PATH=${{env.EXPECTED_ISCC_PATH}}" >> $env:GITHUB_ENV
          
      - name: Set up ENV
        run: echo "BUILD_NAME=${{env.BUILD_NAME_BASE}}_${{matrix.python-arch}}" >> $env:GITHUB_ENV
          
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.python-arch }}
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Compile C extension and create executable
        run: python setup.py build
        
      - name: Build installer via Inno Setup
        run: python inno_setup.py --inno="${{env.ISCC_PATH}}" -o PositionerOutputDir="${{env.INSTALLER_DIR}}" PositionerInstallerName="${{env.BUILD_NAME}}"
      
      - name: Zip "portable" version
        run: 7z a -tzip "${{env.INSTALLER_DIR}}\${{env.BUILD_NAME}}.zip" ${{env.SCRIPT_BUILD_PATH}}
        
      - name: Add assets to release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{env.INSTALLER_DIR}}/*
          
          
      - name: Job summary
        shell: bash
        run: |
          echo "### ✔ Builded successfully [pyhon${{matrix.python-version}} ${{ matrix.python-arch }}]" >> $GITHUB_STEP_SUMMARY
      
      - name: Perf test summary
        shell: bash
        run: |
          echo "MD_REPORT<<EOF" >> $GITHUB_ENV
          echo "<details><summary>🏗 <b>[${{ matrix.python-arch }}]</b> build info</summary>" >> $GITHUB_ENV
          echo -e "<br>" >> $GITHUB_ENV
          echo -e "- [installer] ${{env.BUILD_NAME}}.exe" >> $GITHUB_ENV
          echo -e "- [portable] ${{env.BUILD_NAME}}.zip\n<hr>" >> $GITHUB_ENV
          echo "</details>" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Add report to release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{env.MD_REPORT}}
          append_body: true
